name: flint_hardware
description: A Dart-first hardware abstraction, simulation, and firmware tooling framework.
version: 0.0.1-dev
homepage: https://flintdart.dev
repository: https://github.com/flint-dart/flint-hardware
issue_tracker: https://github.com/flint-dart/flint-hardware/issues

environment:
  sdk: '>=3.4.0 <4.0.0'

platforms:
  linux:
  macos:
  windows:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0

executables:
  flint_hardware: flint_hardware
