import '../compiler/firmware_program.dart';
import '../gpio/gpio.dart';
import 'code_emitter.dart';

/// Emits portable ANSI C (C99) source code from a FirmwareProgram IR.
final class CEmitter implements CodeEmitter {
  const CEmitter();

  @override
  String emit(FirmwareProgram program) {
    final StringBuffer buffer = StringBuffer();
    buffer.writeln('/* Generated by Flint Hardware from declarative Dart IR */');
    buffer.writeln('/* Target: ${program.target.displayName} */');
    buffer.writeln('#include <stdio.h>');
    buffer.writeln('#include <stdbool.h>');
    buffer.writeln('#include <stdint.h>');
    buffer.writeln();
    buffer.writeln('void flint_${program.name}_init(void) {');
    buffer.writeln('    printf("[Flint] Initializing ${program.name}\\n");');

    for (final FirmwareOperation op in program.operations) {
      if (op is ConfigureDigitalOutput) {
        final int val = op.initialLevel == DigitalLevel.high ? 1 : 0;
        buffer.writeln('    /* GPIO ${op.pin} -> Output (initial: $val) */');
      } else if (op is ConfigureDigitalInput) {
        buffer.writeln('    /* GPIO ${op.pin} -> Input (pull: ${op.pull.name}) */');
      } else if (op is ConfigurePwmOutput) {
        buffer.writeln('    /* PWM Pin ${op.pin} -> Freq: ${op.frequencyHz}Hz, Res: ${op.resolutionBits}bit */');
      } else if (op is ConfigureCameraOp) {
        buffer.writeln('    /* Camera -> Res: ${op.config.resolution.label}, Format: ${op.config.format.label} */');
      } else if (op is LoadAiModelOp) {
        buffer.writeln('    /* AI Model -> ${op.descriptor.name} (Arena: ${op.descriptor.tensorArenaSizeKb}KB) */');
      } else if (op is ConfigureBleOp) {
        buffer.writeln('    /* BLE Peripheral -> "${op.config.deviceName}" */');
      } else if (op is ConfigureMeshOp) {
        buffer.writeln('    /* Mesh Swarm -> Group: "${op.config.swarm.identifier}", Channel: ${op.config.channel.number} */');
      }
    }
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln('void flint_${program.name}_run(void) {');
    for (final FirmwareOperation op in program.operations) {
      if (op is RepeatForever) {
        buffer.writeln('    while (true) {');
        for (final FirmwareOperation loopOp in op.operations) {
          if (loopOp is WriteDigitalOutput) {
            final int val = loopOp.level == DigitalLevel.high ? 1 : 0;
            buffer.writeln('        /* Write GPIO ${loopOp.pin} = $val */');
          } else if (loopOp is SetPwmDutyFraction) {
            buffer.writeln('        /* Set PWM Pin ${loopOp.pin} Duty = ${(loopOp.fraction * 100).toStringAsFixed(1)}% */');
          } else if (loopOp is FirmwareDelay) {
            buffer.writeln('        /* Delay ${loopOp.duration.inMilliseconds}ms */');
          } else if (loopOp is FirmwareLog) {
            buffer.writeln('        printf("[Flint] %s\\n", "${loopOp.message}");');
          }
        }
        buffer.writeln('    }');
      }
    }
    buffer.writeln('}');
    return buffer.toString();
  }
}
