import '../compiler/firmware_program.dart';
import '../gpio/gpio.dart';
import 'code_emitter.dart';

/// Emits Arduino / PlatformIO compatible Modern C++ from a FirmwareProgram IR.
final class CppEmitter implements CodeEmitter {
  const CppEmitter();

  @override
  String emit(FirmwareProgram program) {
    final StringBuffer buffer = StringBuffer();
    buffer.writeln('// Generated by Flint Hardware from declarative Dart IR');
    buffer.writeln('// Target: ${program.target.displayName}');
    buffer.writeln('#include <Arduino.h>');
    buffer.writeln();

    for (final FirmwareOperation op in program.operations) {
      if (op is ConfigureDigitalOutput) {
        buffer.writeln('const int PIN_${op.pin} = ${op.pin};');
      } else if (op is ConfigureDigitalInput) {
        buffer.writeln('const int PIN_${op.pin} = ${op.pin};');
      }
    }
    buffer.writeln();
    buffer.writeln('void setup() {');
    buffer.writeln('    Serial.begin(115200);');
    buffer.writeln('    Serial.println("[Flint] Starting ${program.name}");');

    for (final FirmwareOperation op in program.operations) {
      if (op is ConfigureDigitalOutput) {
        buffer.writeln('    pinMode(PIN_${op.pin}, OUTPUT);');
        final String val = op.initialLevel == DigitalLevel.high ? 'HIGH' : 'LOW';
        buffer.writeln('    digitalWrite(PIN_${op.pin}, $val);');
      } else if (op is ConfigureDigitalInput) {
        final String mode = op.pull == PinPull.up ? 'INPUT_PULLUP' : 'INPUT';
        buffer.writeln('    pinMode(PIN_${op.pin}, $mode);');
      } else if (op is ConfigurePwmOutput) {
        buffer.writeln('    // PWM Pin ${op.pin} initialized at ${op.frequencyHz}Hz');
      } else if (op is ConfigureCameraOp) {
        buffer.writeln('    Serial.println("[Flint] Camera enabled: ${op.config.resolution.label}");');
      } else if (op is LoadAiModelOp) {
        buffer.writeln('    Serial.println("[Flint] AI Model loaded: ${op.descriptor.name}");');
      } else if (op is ConfigureBleOp) {
        buffer.writeln('    Serial.println("[Flint] BLE Peripheral ready: ${op.config.deviceName}");');
      } else if (op is ConfigureMeshOp) {
        buffer.writeln('    Serial.println("[Flint] Mesh Swarm ready: Group ${op.config.swarm.identifier}");');
      }
    }
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln('void loop() {');
    for (final FirmwareOperation op in program.operations) {
      if (op is RepeatForever) {
        for (final FirmwareOperation loopOp in op.operations) {
          if (loopOp is WriteDigitalOutput) {
            final String val = loopOp.level == DigitalLevel.high ? 'HIGH' : 'LOW';
            buffer.writeln('    digitalWrite(PIN_${loopOp.pin}, $val);');
          } else if (loopOp is SetPwmDutyFraction) {
            final int duty = (loopOp.fraction.clamp(0.0, 1.0) * 255).round();
            buffer.writeln('    analogWrite(PIN_${loopOp.pin}, $duty);');
          } else if (loopOp is FirmwareDelay) {
            buffer.writeln('    delay(${loopOp.duration.inMilliseconds});');
          } else if (loopOp is FirmwareLog) {
            buffer.writeln('    Serial.println("[Flint] ${loopOp.message}");');
          }
        }
      }
    }
    buffer.writeln('}');
    return buffer.toString();
  }
}
