import '../compiler/firmware_program.dart';
import '../gpio/gpio.dart';
import 'code_emitter.dart';

/// Emits MicroPython / CircuitPython code from a FirmwareProgram IR.
final class MicroPythonEmitter implements CodeEmitter {
  const MicroPythonEmitter();

  @override
  String emit(FirmwareProgram program) {
    final StringBuffer buffer = StringBuffer();
    buffer.writeln('# Generated by Flint Hardware from declarative Dart IR');
    buffer.writeln('# Target: ${program.target.displayName}');
    buffer.writeln('import time');
    buffer.writeln('from machine import Pin, PWM');
    buffer.writeln();

    for (final FirmwareOperation op in program.operations) {
      if (op is ConfigureDigitalOutput) {
        final int val = op.initialLevel == DigitalLevel.high ? 1 : 0;
        buffer.writeln('pin_${op.pin} = Pin(${op.pin}, Pin.OUT, value=$val)');
      } else if (op is ConfigureDigitalInput) {
        final String pull = op.pull == PinPull.up
            ? ', Pin.PULL_UP'
            : op.pull == PinPull.down
                ? ', Pin.PULL_DOWN'
                : '';
        buffer.writeln('pin_${op.pin} = Pin(${op.pin}, Pin.IN$pull)');
      } else if (op is ConfigurePwmOutput) {
        buffer.writeln('pwm_${op.pin} = PWM(Pin(${op.pin}))');
        buffer.writeln('pwm_${op.pin}.freq(${op.frequencyHz})');
      } else if (op is ConfigureCameraOp) {
        buffer.writeln('# Camera configured: ${op.config.resolution.label}');
      } else if (op is LoadAiModelOp) {
        buffer.writeln('# AI Model: ${op.descriptor.name}');
      } else if (op is ConfigureBleOp) {
        buffer.writeln('# BLE Peripheral: ${op.config.deviceName}');
      } else if (op is ConfigureMeshOp) {
        buffer.writeln('# ESP-NOW Swarm: ${op.config.swarm.identifier} (ch: ${op.config.channel.number})');
      }
    }
    buffer.writeln();
    buffer.writeln('print("[Flint] Starting ${program.name} on MicroPython")');
    buffer.writeln();

    for (final FirmwareOperation op in program.operations) {
      if (op is RepeatForever) {
        buffer.writeln('while True:');
        for (final FirmwareOperation loopOp in op.operations) {
          if (loopOp is WriteDigitalOutput) {
            final int val = loopOp.level == DigitalLevel.high ? 1 : 0;
            buffer.writeln('    pin_${loopOp.pin}.value($val)');
          } else if (loopOp is SetPwmDutyFraction) {
            final int dutyU16 = (loopOp.fraction.clamp(0.0, 1.0) * 65535).round();
            buffer.writeln('    pwm_${loopOp.pin}.duty_u16($dutyU16)');
          } else if (loopOp is FirmwareDelay) {
            final double secs = loopOp.duration.inMicroseconds / 1000000.0;
            buffer.writeln('    time.sleep($secs)');
          } else if (loopOp is FirmwareLog) {
            buffer.writeln('    print("[Flint] ${loopOp.message}")');
          }
        }
      }
    }
    return buffer.toString();
  }
}
