import '../compiler/firmware_program.dart';
import '../gpio/gpio.dart';
import 'code_emitter.dart';

/// Emits ROS 2 Python (rclpy) robotics node code from a FirmwareProgram IR.
final class Ros2PythonEmitter implements CodeEmitter {
  const Ros2PythonEmitter();

  @override
  String emit(FirmwareProgram program) {
    final StringBuffer buffer = StringBuffer();
    buffer.writeln('#!/usr/bin/env python3');
    buffer.writeln('# Generated by Flint Hardware: ROS 2 Robotics Node');
    buffer.writeln('# Target: ${program.target.displayName}');
    buffer.writeln('import rclpy');
    buffer.writeln('from rclpy.node import Node');
    buffer.writeln('from std_msgs.msg import String, Bool, Float32');
    buffer.writeln();
    buffer.writeln('class ${program.name.replaceAll('_', ' ').split(' ').map((s) => s.isNotEmpty ? s[0].toUpperCase() + s.substring(1) : '').join('')}Node(Node):');
    buffer.writeln('    def __init__(self):');
    buffer.writeln('        super().__init__("${program.name}")');
    buffer.writeln('        self.get_logger().info("[Flint] Starting ROS 2 Node: ${program.name}")');
    buffer.writeln();

    for (final FirmwareOperation op in program.operations) {
      if (op is ConfigureDigitalOutput) {
        buffer.writeln('        self.pub_gpio_${op.pin} = self.create_publisher(Bool, "flint/gpio_${op.pin}/state", 10)');
      } else if (op is ConfigurePwmOutput) {
        buffer.writeln('        self.pub_pwm_${op.pin} = self.create_publisher(Float32, "flint/pwm_${op.pin}/duty", 10)');
      } else if (op is ConfigureCameraOp) {
        buffer.writeln('        # Camera pipeline configured for ${op.config.resolution.label}');
      } else if (op is LoadAiModelOp) {
        buffer.writeln('        # On-device AI Model: ${op.descriptor.name}');
      } else if (op is ConfigureMeshOp) {
        buffer.writeln('        self.pub_mesh = self.create_publisher(String, "flint/mesh/${op.config.swarm.identifier}", 10)');
      }
    }
    buffer.writeln();
    buffer.writeln('        # Periodic control loop timer (10 Hz)');
    buffer.writeln('        self.timer = self.create_timer(0.1, self.loop_callback)');
    buffer.writeln();
    buffer.writeln('    def loop_callback(self):');
    for (final FirmwareOperation op in program.operations) {
      if (op is RepeatForever) {
        for (final FirmwareOperation loopOp in op.operations) {
          if (loopOp is WriteDigitalOutput) {
            final String val = loopOp.level == DigitalLevel.high ? 'True' : 'False';
            buffer.writeln('        msg = Bool(data=$val)');
            buffer.writeln('        self.pub_gpio_${loopOp.pin}.publish(msg)');
          } else if (loopOp is SetPwmDutyFraction) {
            buffer.writeln('        msg = Float32(data=${loopOp.fraction.toStringAsFixed(2)})');
            buffer.writeln('        self.pub_pwm_${loopOp.pin}.publish(msg)');
          } else if (loopOp is FirmwareLog) {
            buffer.writeln('        self.get_logger().info("${loopOp.message}")');
          }
        }
      }
    }
    buffer.writeln();
    buffer.writeln('def main(args=None):');
    buffer.writeln('    rclpy.init(args=args)');
    buffer.writeln('    node = ${program.name.replaceAll('_', ' ').split(' ').map((s) => s.isNotEmpty ? s[0].toUpperCase() + s.substring(1) : '').join('')}Node()');
    buffer.writeln('    try:');
    buffer.writeln('        rclpy.spin(node)');
    buffer.writeln('    except KeyboardInterrupt:');
    buffer.writeln('        pass');
    buffer.writeln('    finally:');
    buffer.writeln('        node.destroy_node()');
    buffer.writeln('        rclpy.shutdown()');
    buffer.writeln();
    buffer.writeln('if __name__ == "__main__":');
    buffer.writeln('    main()');
    return buffer.toString();
  }
}
